export enum ActionType {
  OPEN_SIDEBAR = "OPEN_SIDEBAR",
  CLOSE_SIDEBAR = "CLOSE_SIDEBAR",

  IS_LOADING = "IS_LOADING",
  IS_ERROR = "IS_ERROR",
  GET_USERS = "GET_USERS",
  UPDATE_USER = "UPDATE_USER",
}
